version: 2

project_name: terramate-atlantis-config

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: terramate-atlantis-config
    main: .
    binary: terramate-atlantis-config
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/devops-roast/terramate-atlantis-config/cmd.Version={{.Version}}
      - -X github.com/devops-roast/terramate-atlantis-config/cmd.Commit={{.Commit}}
      - -X github.com/devops-roast/terramate-atlantis-config/cmd.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: terramate-atlantis-config
    repository:
      owner: devops-roast
      name: homebrew-tap
    homepage: https://github.com/devops-roast/terramate-atlantis-config
    description: Generate Atlantis config for Terramate projects
    binaries:
      - terramate-atlantis-config
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terramate-atlantis-config"]
          end

nfpms:
  - id: packages
    package_name: terramate-atlantis-config
    maintainer: devops-roast <devops-roast@users.noreply.github.com>
    vendor: devops-roast
    homepage: https://github.com/devops-roast/terramate-atlantis-config
    description: Generate Atlantis config for Terramate projects
    license: MIT
    formats:
      - deb
      - rpm
