repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: [--maxkb=1024]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
        name: detect hardcoded secrets

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w -s
        language: system
        types: [go]

      - id: go-imports
        name: goimports
        entry: goimports -w -local github.com/devops-roast/terramate-atlantis-config
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: bash -c 'go mod tidy'
        language: system
        files: (\.go|go\.mod|go\.sum)$
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'mise exec -- golangci-lint run --fix --timeout=3m ./...'
        language: system
        types: [go]
        pass_filenames: false
        require_serial: true
