[settings]
experimental = true

[tools]
go = "1.25"
"aqua:golangci/golangci-lint" = "2.11.4"
"aqua:mvdan/gofumpt" = "0.7.0"
"aqua:pre-commit/pre-commit" = "4.2.0"

[tools."go:golang.org/x/tools/cmd/goimports"]
version = "latest"

[env]
GOTOOLCHAIN = "auto"
