[tools]
go = "1.25"
"aqua:mvdan/gofumpt" = "0.7.0"
"aqua:pre-commit/pre-commit" = "4.2.0"

[tools."go:github.com/golangci/golangci-lint/cmd/golangci-lint"]
version = "v1.64.8"

[tools."go:golang.org/x/tools/cmd/goimports"]
version = "latest"

[env]
GOTOOLCHAIN = "auto"
