---
name: release please

permissions:
  contents: write
  pull-requests: write

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [main]

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: devops-roast/github-actions/.github/workflows/release-please-standard.yaml@main
    secrets: inherit
    with:
      type: simple
