---
name: release please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"

jobs:
  release-please:
    uses: devops-roast/github-actions/.github/workflows/release-please-standard.yaml@main
    secrets: inherit
    with:
      type: simple
